spring:
  application:
    name: sys-server
  datasource:
    # Spring Datasource Settings
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sys?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
    dbcp2:
      initial-size: 5
      min-idle: 5
      test-on-borrow: true
  cache:
    cache-names:
    - CACHE_KEY
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

      
server:
  port: 8090
  
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/#,http://localhost:8762/eureka/

logging:
  file: logs/log.log
  level:
    tk:
      mybatis:
        TRACE


global:
  upload:
    path: /upload/
    docBase: /service/upload/


mybatis:
  type-aliases-package: com.primeton.sys.*.model
  mapper-locations:
  - classpath:mapper/*.xml
mapper:
  mappers:
  - com.primeton.sys.dao.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql


  
